ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps.discord]
path = "out/DiscordTrap.sol/DiscordTrap.json"
response_contract = "0xC6EFE7E82dda80Bb4A1637296F3F98424Ea9c0Be"  # ResponseContract
response_function = "respondWithDiscordName(string)"
cooldown_period_blocks = 32
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0xF35e16cE233C9bC0A8a4070bDC776E3f9b407b52"]
address = "0x04416670df4836d5da579b24b3f642076251393a"

[traps.sergeant]
path = "out/SergeantTrap.sol/SergeantTrap.json"
response_contract = "0xC6EFE7E82dda80Bb4A1637296F3F98424Ea9c0Be"
response_function = "respondWithDiscordName(string)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0xF35e16cE233C9bC0A8a4070bDC776E3f9b407b52"]
address = "0xa81b7f5d3da9b70b79abb7274f8e73ba9e6a3140"
